sudo: required
language: bash
services:
  - docker
before_script:
  - docker-compose build data-loader
script: 
  - docker-compose run --rm -e KBC_TEST_TOKEN -e KBC_TEST_URL data-loader composer ci
deploy:
  provider: script
  skip_cleanup: true
  script: ./deploy.sh
  on:
    tags: true  
