sudo: required
language: bash
services:
  - docker
before_script:
  - docker-compose build data-loader
script: docker-compose run --rm -e KBC_TOKEN=$KBC_TOKEN data-loader /code/Tests/run.sh
after_success:
  - docker images
deploy:
  provider: script
  skip_cleanup: true
  script: ./deploy.sh
  on:
    tags: true  
