version: '2'
services:
  data-loader:
    build: .
    image: keboola/data-loader
    tty: true
    stdin_open: true
    command: bash
  dev:
    image: keboola/data-loader
    volumes:
      - ./:/code
    tty: true
    stdin_open: true
    command: bash
    environment:
      - KBC_TEST_URL
      - KBC_TEST_TOKEN
